### ISSUE TITLE
Error while installing via npm

### ISSUE THREAD

**Issue by lmartins** [pcardune/handlebars-loader#6]
Is this related to my setup or an issue with the loader dependencies?

```
npm ERR! peerinvalid The package handlebars does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer handlebars-loader@0.1.6 wants handlebars@~1.3.0
```

**Comment by altano** [comment]
For those of you that were recently hitting this, we were really late in adding handlebars 2.0 support, but it's up on NPM now so you shouldn't have issues.

But, just for future reference, when you hit this kind of error it means you're using a plug-in version that is incompatible with a peer module (e.g. a grunt plugin that is incompatible with the version of grunt you are using).  Please read this blog post for more info, since you should understand peer dependencies if you're using Node: http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by rcolepeterson** [comment]
I am still getting error: Failed to parse package.json data.
